services:
  php:
    build:
      context: .
    container_name: symfony-php
    ports:
      - "8000:80"
    volumes:
      - ./app:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: symfony-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
    ports:
      - "3309:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: symfony-pma
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
