nelmio_api_doc:
    documentation:
        info:
            title: Twitter API
            description: La documentation de l’API des tweets
            version: 1.0.0
        components:
            securitySchemes:
                BearerAuth:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
        security:
            - BearerAuth: []
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc

            